version: "3.7"
services:
  python:
    build: python
    volumes:
      - static:/app/static
    environment:
      - INVENTORY_DB_ENGINE=django.db.backends.mysql
      - INVENTORY_DEBUG_MODE=False
      - INVENTORY_DB_NAME=inventory
      - INVENTORY_DB_USER=inventory
      - INVENTORY_DB_PASSWORD=zbakhKStr543mT_OB/r}actiTSNHOT
      - INVENTORY_DB_HOST=db
      - INVENTORY_DB_PORT=3306
      - INVENTORY_TIME_ZONE=Europe/Berlin
    depends_on:
      - web
    restart: always
  web:
    build: web
    ports:
      - "8000:8000"
    volumes:
      - static:/var/www/static
    restart: always
  db:
    image: maridadb:10
    #volumes: ./inventorydb:/var/lib/mysql
  environment:
     - MYSQL_DATABASE=inventory
     - MYSQL_USER=inventory
     - MYSQL_PASSWORD=zbakhKStr543mT_OB/r}actiTSNHOT
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
